### ISSUE TITLE
Add visual output to examples

### ISSUE THREAD

**Issue by dedoco** [j-i-l/FlowVisExample#1]
Hi,

Would it be too much asked to add the resulting plots to the example?

I'm hesitating to give this a try, it would make my decision a lot easier, to see what this package produces.

**Comment by j-i-l** [comment]
Will do

**Comment by j-i-l** [comment]
Added plots with visualizations of the different states (before attack, the attack, after attack, etc.) for the minimal example.
The choice of colors is certainly not ideal, but can easily be improved by adapting the `config.json` file.

**Comment by dedoco** [comment]
@j-i-l cool, thanks a lot!
